services:
  quizserver:
    image: philip000ict/quizserver:v2
    container_name: quizserver-v2
    networks:
      - shared-db-net
    volumes:
      - ./:/app
      - ./templates:/app/templates
      - ./static/img:/app/static/img
    env_file:
      - .env
    ports:
      - "5055:5000"

networks:
  shared-db-net:
    external: true
    name: shared-db-net

