services:
  quizserver:
    image: philip000ict/quizserver:v2.1
    container_name: quizserver-v2.1
    networks:
      - shared-db-net
    env_file:
      - .env
    ports:
      - "5055:5000"

networks:
  shared-db-net:
    external: true
    name: shared-db-net

